FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY ui /app/ui
COPY utils /app/utils
COPY ml_model /app/ml_model
COPY .env.example /app/.env

CMD ["streamlit", "run", "ui/app.py", "--server.port=8501", "--server.enableXsrfProtection=false"]

