FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY api /app/api
COPY utils /app/utils
COPY ml_model /app/ml_model
COPY alerting /app/alerting
COPY sandbox /app/sandbox
COPY .env.example /app/.env

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]

